In [3]:
import numpy as np

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
a[:,0]

array([1, 4, 7])

In [8]:
a[:,1]

array([2, 5, 8])

In [9]:
a[0, :]

array([1, 2, 3])

In [10]:
a[1, :]

array([4, 5, 6])

In [11]:
a[...,0]

array([1, 4, 7])

In [12]:
a[:,[0]]

array([[1],
       [4],
       [7]])

In [13]:
a[:, 0+1]

array([2, 5, 8])

In [14]:
a[:,0,np.newaxis]

array([[1],
       [4],
       [7]])

In [15]:
a[0,0]

1

In [16]:
a[0][0]

1

In [17]:
a[1][2]

6

In [18]:
a[1,2]

6

In [19]:
a[[1], [2]]

array([6])

In [20]:
a[0]

array([1, 2, 3])

In [22]:
a[0,:]

array([1, 2, 3])

In [23]:
a[[0],:]

array([[1, 2, 3]])

In [24]:
a[0, np.newaxis]

array([[1, 2, 3]])

In [25]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [26]:
a[[0,2],:]

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
a[a>0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[a > 5]

array([6, 7, 8, 9])