In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
s = a[1:3]
s

array([2, 3])

In [5]:
s[0] = 1000

In [6]:
a

array([   1, 1000,    3,    4,    5])

In [7]:
c = a[[1,3]].copy()
c

array([1000,    4])

In [8]:
c[0] = 888

In [9]:
a

array([   1, 1000,    3,    4,    5])

In [10]:
c

array([888,   4])