In [1]:
import numpy as np

In [2]:
a = np.array([-2,-1,0,1,2])
b = np.array([2,2,2,2,2])

In [3]:
a + b

array([0, 1, 2, 3, 4])

In [4]:
a - b

array([-4, -3, -2, -1,  0])

In [5]:
a * b

array([-4, -2,  0,  2,  4])

In [6]:
a / b

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [7]:
a ** b

array([4, 1, 0, 1, 4])

In [8]:
c = np.array([2])

In [9]:
a + c

array([0, 1, 2, 3, 4])

In [10]:
a - c

array([-4, -3, -2, -1,  0])

In [11]:
a * c

array([-4, -2,  0,  2,  4])

In [12]:
a / c

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [13]:
a ** c

array([4, 1, 0, 1, 4])

In [14]:
v1 = np.array([[-2,-1,0,1,2]])
v2 = np.array([[1],[2],[3]])

In [15]:
v1 + v2

array([[-1,  0,  1,  2,  3],
       [ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5]])

In [16]:
v1 * v2

array([[-2, -1,  0,  1,  2],
       [-4, -2,  0,  2,  4],
       [-6, -3,  0,  3,  6]])