In [1]:
import numpy as np

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b = np.reshape(a, (3,4))

In [4]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
c = np.reshape(a, (2,3,2))

In [6]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [7]:
a = np.array([[1,2], [3,4]])
b = np.reshape(a, -1)

In [8]:
b

array([1, 2, 3, 4])

In [9]:
a = np.arange(6).reshape((2,3))

In [10]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
b = np.reshape(a, (3,2), order='F')

In [12]:
b

array([[0, 4],
       [3, 2],
       [1, 5]])